---
spring:
  application:
    name: capitol-city-flyers
  profiles:
    default:
      - development
      - is-acceptance
  web:
    locale: en_US
    resources:
      add-mappings: false
server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
logging:
  level:
    ccf: DEBUG
---
spring:
  config:
    activate:
      on-profile: development
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: in-aws-ebs
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: is-production
google:
  analytics:
    site-id: G-H9QC01BM3Z
